length:
  digit_6: 6
  digit_50: 50
  digit_140: 140
  digit_255: 255
email_regrex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
email_link: https://gravatar.com/emails
pixels:
  digit_50: 50
  digit_80: 80
per_page:
  digit_10: 10
  digit_5: 5
link_expired:
  hours_2: 2
